version: '3'

services:
  milleniumfalconchallenge-svc:
    build:
      context: .
      dockerfile: Dockerfile
    image: milleniumfalconchallenge
    container_name: milleniumfalconchallenge-ctn
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:38190
      - MILLENIUMFALCONPATH=/app/millennium-falcon.json
    # Example configuration for configurable MILLENIUMFALCONPATH
    # Don't forget to update "routes_db" (either relative to MILLENIUMFALCONPAT or absolute)
    #   - MILLENIUMFALCONPATH=/data/example1/millennium-falcon.json
    # volumes:
    #   - {PathToDataikuRepository}\millenium-falcon-challenge\examples:/data
    ports:
      - 38190:38190